version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gst_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gst_network

  app:
    build: .
    container_name: gst_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MAX_REQUESTS_PER_MINUTE=${MAX_REQUESTS_PER_MINUTE}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    stdin_open: true
    tty: true
    networks:
      - gst_network

volumes:
  mysql_data:


networks:
  gst_network:
    driver: bridge
